export interface NCVAClub {
  id: string
  name: string
  shortName?: string
  address: string
  city: string
  state: string
  zip: string
  website?: string
  email?: string
  phone?: string
  director?: string
  notes?: string
  isOurs?: boolean
}

export const NCVA_CLUBS: NCVAClub[] = [
  {
    id: "uvac",
    name: "Urban Volleyball Athletic Club",
    shortName: "UVAC",
    address: "1970 Morrill Ave",
    city: "San Jose",
    state: "CA",
    zip: "95132",
    website: "urbanvolleyballac.com",
    isOurs: true,
  },
  {
    id: "vision",
    name: "Vision Volleyball Club",
    shortName: "Vision",
    address: "1742 Stone Ave",
    city: "San Jose",
    state: "CA",
    zip: "95128",
    website: "visionvolleyball.com",
  },
  {
    id: "academy",
    name: "Academy Volleyball Club",
    shortName: "Academy",
    address: "3151 Edison Way",
    city: "Redwood City",
    state: "CA",
    zip: "94063",
    phone: "(650) 384-9440",
    website: "academyvolleyball.com",
    notes: "Also trains in Burlingame",
  },
  {
    id: "red-rock",
    name: "Red Rock Volleyball Club",
    shortName: "Red Rock",
    address: "3151 Edison Way",
    city: "Redwood City",
    state: "CA",
    zip: "94063",
    phone: "(650) 868-1832",
    email: "travel@redrockvolleyball.com",
    website: "redrockvolleyball.com",
    notes: "Multiple locations: SF, Campbell, Alameda, Danville, Martinez, Walnut Creek",
  },
  {
    id: "mvvc",
    name: "Mountain View Volleyball Club",
    shortName: "MVVC",
    address: "477 N Mathilda Ave",
    city: "Sunnyvale",
    state: "CA",
    zip: "94085",
    phone: "(408) 329-0488",
    website: "mvvclub.com",
    director: "Mike Rubin",
    email: "mikerubin@mvvclub.com",
  },
  {
    id: "synergy-force",
    name: "SynergyForce Volleyball Club",
    shortName: "SynergyForce",
    address: "10050 Foothills Blvd",
    city: "Roseville",
    state: "CA",
    zip: "95747",
    phone: "(916) 250-8130",
    website: "synergyforcevbc.com",
  },
  {
    id: "absolute",
    name: "Absolute Volleyball Club",
    shortName: "Absolute",
    address: "2145 Francisco Blvd E",
    city: "San Rafael",
    state: "CA",
    zip: "94901",
    phone: "(415) 902-5511",
    website: "absolutevb.com",
  },
  {
    id: "sf-elite",
    name: "SF Elite Volleyball Club",
    shortName: "SF Elite",
    address: "1422 San Mateo Ave",
    city: "South San Francisco",
    state: "CA",
    zip: "94080",
    phone: "(650) 273-1055",
    email: "info@elitesportscenters.com",
    website: "sfelitevbc.com",
  },
  {
    id: "norcal",
    name: "NorCal Volleyball Club",
    shortName: "NorCal",
    address: "789 N Canyons Pkwy",
    city: "Livermore",
    state: "CA",
    zip: "94551",
    phone: "(925) 708-4654",
    email: "mhnorcal@gmail.com",
    website: "norcalvbc.com",
  },
  {
    id: "bay-area-eagles",
    name: "Bay Area Eagles Volleyball Club",
    shortName: "BA Eagles",
    address: "427 Alvarado St",
    city: "San Leandro",
    state: "CA",
    zip: "94577",
    website: "bayareaeagles.com",
    notes: "Trains at John Muir Middle School, 1444 Williams St",
  },
  {
    id: "vibe",
    name: "Vibe Volleyball Club",
    shortName: "Vibe",
    address: "2640 Shadelands Dr",
    city: "Walnut Creek",
    state: "CA",
    zip: "94598",
    phone: "(925) 300-6166",
    email: "info@vbvibe.com",
    website: "vbvibe.com",
    notes: "Also trains in Danville, Orinda",
  },
  {
    id: "rage",
    name: "RAGE Volleyball Club",
    shortName: "RAGE",
    address: "811 W River Rd",
    city: "Ripon",
    state: "CA",
    zip: "95366",
    website: "ragevball.com",
    notes: "Also trains in Lodi and Livermore",
  },
  {
    id: "marin-juniors",
    name: "Marin Juniors Volleyball Club",
    shortName: "Marin Juniors",
    address: "PO Box 151674",
    city: "San Rafael",
    state: "CA",
    zip: "94915",
    phone: "(415) 250-7480",
    website: "marinjuniors.com",
    notes: "Trains at Pickleweed Community Center & Marin Academy HS",
  },
  {
    id: "imua",
    name: "IMUA Volleyball Club",
    shortName: "IMUA",
    address: "266F Reservation Road #505",
    city: "Marina",
    state: "CA",
    zip: "93933",
    website: "imuavbc.com",
    notes: "Founded 1988 · indoor, beach & grass",
  },
  {
    id: "sf-tremors",
    name: "SF Tremors Volleyball Club",
    shortName: "SF Tremors",
    address: "999 Brotherhood Way",
    city: "San Francisco",
    state: "CA",
    zip: "94132",
    website: "sftremors.com",
    notes: "Trains at Holy Trinity Gym",
  },
  {
    id: "slainte",
    name: "Slainte Volleyball Club",
    shortName: "Slainte",
    address: "601 Van Ness Ave Ste E730",
    city: "San Francisco",
    state: "CA",
    zip: "94109",
    phone: "(650) 755-1707",
    website: "slaintevolleyball.org",
  },
  {
    id: "panda",
    name: "Panda Volleyball Club",
    shortName: "Panda",
    address: "1071 Del Cambre Dr",
    city: "San Jose",
    state: "CA",
    zip: "95129",
    phone: "(408) 685-1589",
    email: "pandavolleyball2022@gmail.com",
    website: "pandavolleyballclub.net",
    director: "Yilin Shangguan",
    notes: "Also trains at 4120 Middlefield Rd, Palo Alto",
  },
  {
    id: "dvvc",
    name: "Diablo Valley Volleyball Club",
    shortName: "DVVC",
    address: "PO Box 69",
    city: "Concord",
    state: "CA",
    zip: "94522",
    phone: "(925) 451-6581",
    email: "info@diablovolleyball.org",
    website: "diablovolleyball.org",
    notes: "Trains at Tice Valley Gym, 2055 Tice Valley Blvd, Walnut Creek",
  },
  {
    id: "delta-valley",
    name: "Delta Valley Volleyball Club",
    shortName: "Delta Valley",
    address: "PO Box 8322",
    city: "Stockton",
    state: "CA",
    zip: "95208",
    phone: "(209) 629-5898",
    email: "deltavalleyvb@gmail.com",
    website: "deltavalleyvbc.net",
    notes: "Trains at 1230 S Central Ave, Lodi (Lodi Academy)",
  },
  {
    id: "encore",
    name: "Encore Volleyball Club",
    shortName: "Encore",
    address: "2575 E Bayshore Rd",
    city: "Redwood City",
    state: "CA",
    zip: "94063",
    phone: "(650) 512-2304",
    email: "encoreleadership@encorevolleyball.com",
    website: "encorevolleyball.com",
  },
  {
    id: "turlock-crush",
    name: "Turlock Crush Volleyball Club",
    shortName: "Turlock Crush",
    address: "2882 Ahlem Ave",
    city: "Turlock",
    state: "CA",
    zip: "95382",
    phone: "(209) 535-5512",
    email: "TurlockCrush@gmail.com",
    website: "turlockcrushvolleyball.com",
  },
  {
    id: "golden-state",
    name: "Golden State Volleyball Club",
    shortName: "Golden State",
    address: "",
    city: "Manteca",
    state: "CA",
    zip: "",
    email: "goldenstatevbc@gmail.com",
    website: "goldenstatevolleyballclub.com",
  },
  {
    id: "city-beach",
    name: "City Beach Volleyball Club",
    shortName: "City Beach",
    address: "4020 Technology Pl",
    city: "Fremont",
    state: "CA",
    zip: "94538",
    phone: "(408) 654-9330",
    website: "citybeachvb.com",
    notes: "Also has Santa Clara location",
  },
  {
    id: "aftershock",
    name: "Aftershock Volleyball Club",
    shortName: "Aftershock",
    address: "PO Box 8023",
    city: "Santa Rosa",
    state: "CA",
    zip: "95407",
    phone: "(707) 479-9645",
    email: "craig@aftershockvolleyball.com",
    website: "aftershockvolleyball.com",
    director: "Craig Hardisty",
  },
  {
    id: "club-solano",
    name: "Club Solano Volleyball Club",
    shortName: "Club Solano",
    address: "PO Box 336",
    city: "Suisun City",
    state: "CA",
    zip: "94585",
    website: "clubsolano.com",
  },
  {
    id: "spark",
    name: "Spark Volleyball Club",
    shortName: "Spark",
    address: "",
    city: "Lodi",
    state: "CA",
    zip: "95242",
    phone: "(209) 401-7418",
    email: "svcmail88@gmail.com",
    website: "sparkvolleyball.com",
    director: "Juan Martinez",
  },
  {
    id: "golden-bear",
    name: "Golden Bear Volleyball Club",
    shortName: "Golden Bear",
    address: "951-2 Old County Rd #161",
    city: "Belmont",
    state: "CA",
    zip: "94002",
    website: "goldenbearvolleyball.com",
  },
  {
    id: "club-prime",
    name: "Club Prime Volleyball",
    shortName: "CPV",
    address: "",
    city: "Elk Grove",
    state: "CA",
    zip: "",
    website: "clubprimevball.com",
    notes: "Non-profit · Galt, Lodi, Elk Grove, Sacramento, Stockton area",
  },
  {
    id: "lakas",
    name: "Lakas Volleyball Club",
    shortName: "Lakas",
    address: "3532 Arden Rd",
    city: "Hayward",
    state: "CA",
    zip: "94545",
    email: "lakasvb@gmail.com",
    website: "lakasvb.com",
    notes: "Trains at House of Hustle · Mailing: 4082 Polonius Cir, Fremont 94555",
  },
  {
    id: "lava-west",
    name: "LAVA West Volleyball Club",
    shortName: "LAVA West",
    address: "",
    city: "Los Angeles",
    state: "CA",
    zip: "",
    website: "lavavolleyball.com",
    notes: "Southern California club",
  },
]

export function getClubById(id: string): NCVAClub | undefined {
  return NCVA_CLUBS.find((c) => c.id === id)
}

export function searchClubs(query: string): NCVAClub[] {
  const q = query.toLowerCase()
  return NCVA_CLUBS.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.shortName?.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q)
  )
}

export function getClubFullAddress(club: NCVAClub): string {
  const parts = [club.address, club.city, `${club.state} ${club.zip}`.trim()].filter(Boolean)
  return parts.join(", ")
}
